#
# Site Info
title: 'Cuaderno de bitácora de un gestor de APIs'
tagline: 'donde principalmente hablo de, ¡oh sorpresa!, gestión de APIs'
description: 'Mi cuaderno de bitácora, donde principalmente hablo de gestión de APIs.'
baseurl: "/codinfox-lanyon"
url: http://luzbel.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: sjblanes
  description: Un señor que se gana la vida ayudándote a <strong>gestionar tus APIs</strong>.
#  gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/sebastianblanes
    github:    https://github.com/luzbel
    # facebook:  <hide>
    twitter:   https://twitter.com/UCZ443
    #weibo:     http://weibo.com/41173780
    email:     http://www.google.com/recaptcha/mailhide/d?k=01iNfZFgkhPfOwGK2_m0Xrug==&c=vrWlHe-RPOFhSGrpeXA8abLyI-FOT_u1Pf5-GJMM1eeUrrXAj_iHaxd3kxc9Zrjm

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - 'http://luzbel.github.io/codinfox-lanyon'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

home:
  image: /public/img/Luzbel_Retiro.512px.JPG
  caption: Original by Magnificus (Own work) [<a href="http://www.gnu.org/copyleft/fdl.html">GFDL</a> or <a href="http://creativecommons.org/licenses/by-sa/3.0">CC BY-SA 3.0</a>], <a href="https://commons.wikimedia.org/wiki/File%3ALuzbel_Retiro.JPG">via Wikimedia Commons</a>

# Puglins
mathjax: true # whether support mathjax
#google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
google_analytics_token:
#disqus_short_name: 'your_short_name' # leave blank if you don't want disqus
disqus_short_name: 

